name: qr_code
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get: 4.6.5
  lottie: ^3.1.0
  open_file: ^3.2.1
  path_provider: ^2.0.11
  pdf: ^3.3.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - lib/assets/images/logo.png
   - lib/assets/images/signup.png
   - lib/assets/images/login.png
   - lib/assets/lottie/animation.json
   - lib/assets/images/qr.png
   - lib/assets/images/file.png
   - lib/assets/images/add.png
   - lib/assets/images/list.png
   - lib/assets/images/ihLogo.png
   - lib/assets/images/analysis.png
   - lib/assets/images/graph.png